COMMAND: "lp user %player% Kaseya parent set donator"
CLAIMED_MESSAGE: "&aYou have claimed your free rank."
ALREADY_CLAIMED_MESSAGE: "&cYou have already claimed your free rank."
disabled_message: "&cThe Free Rank is currently disabled."

can_claim: true
claimed_players: {}

